export const SET_SELECTED_ID_SUCESS = 'SET_SELECTED_ID_SUCESS';

export const SET_SELECTED_NAME_SUCESS = 'SET_SELECTED_NAME_SUCESS';

export const SET_SELECTED_DETAIL_SUCESS = 'SET_SELECTED_DETAIL_SUCESS';

export const SET_DATA = 'SET_DATA';
